version: "3.5"

services:
  postgres:
    image: postgres:12-alpine
    command: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: